# Generated by Django 5.2.3 on 2025-06-28 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending',
                     'Pending'),
                    ('in_progress',
                     'In Progress'),
                    ('completed',
                     'Completed'),
                    ('cancelled',
                     'Cancelled')],
                default='in_progress',
                max_length=20),
        ),
    ]
